on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build_dev_jar:
    name: Build DEV jars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup JDK
      uses: actions/setup-java@v4.3.0
      with:
        distribution: 'adopt'
        java-version: '17'
        java-package: jdk
        architecture: x64
    - name: Build with Maven
      run: |
        mvn install
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "git_hash=$git_hash" >> $GITHUB_ENV
        echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
    - name: Upload Plugin jar
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-${{ env.snapshotVersion }}-${{ env.git_hash }}.jar
        path: ${{ env.artifactPath }}/TDRPlaytime-${{ steps.project.outputs.version }}.jar
    - name: Sleep for 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        file: ${{ env.artifactPath }}/TDRPlaytime-${{ steps.project.outputs.version }}.jar
        message: "New Playtime build: ${{ steps.project.outputs.version }} - ${{ env.git_hash }}\n${{ env.BRANCH_NAME  }}\n${{ github.event.head_commit.message }}"
        color: "#48f442"
        username: "Playtime Builds"