on: [release,workflow_dispatch]
name: Build plugin for all platforms
jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        downloadSource: [ GITHUB, SPIGOT, HANGAR, MODRINTH, CURSE_FORGE ]
        version: [ 1.16.5, 1.15.2, 1.14.4, 1.13.2, 1.12.2, 1.11.2, 1.10.2, 1.9.4 ]
        java-version: [ 8 ]
        include:
          - version: 1.17.1
            java-version: 16
          - version: 1.18.2
            java-version: 17
          - version: 1.19.4
            java-version: 17
          - version: 1.20.4
            java-version: 17
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: '22'
          java-package: jdk
          architecture: x64
      - name: Set downloadSource in plugin.yml
        run: |
          sed -i "s/downloadSource:.*/downloadSource: '${{ matrix.downloadSource }}'/" src/main/resources/plugin.yml
          cat src/main/resources/plugin.yml
      - name: Build with Maven
        run: |
          mvn install
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Upload Plugin jar to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Plugin-${{ env.snapshotVersion }}-${{ matrix.downloadSource }}.jar
          path: ${{ env.artifactPath }}/TDRPlaytime-${{ steps.project.outputs.version }}.jar
      - name: Test Plugin - ${{ matrix.version }}
        uses: GamerCoder215/TestMC@v1.0.0
        with:
          path: ${{ env.artifactPath }}/TDRPlaytime-${{ steps.project.outputs.version }}.jar
          runtime: 'paper'
          version: ${{ matrix.version }}
      - name: Upload Plugin jar to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.artifactPath }}/TDRPlaytime-${{ steps.project.outputs.version }}.jar
          tag_name: ${{ env.snapshotVersion }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.snapshotVersion }}
          release_notes: ${{ env.snapshotVersion }}
          prerelease: true
          draft: false
          overwrite: true
