name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          architecture: x64
      - name: Build with Maven
        id: build
        run: |
          mvn install
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Setup Shared Variables
        id: setup_shared
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = github.context.payload.pull_request?.number;
            const repo = github.context.repo.repo;
            const owner = github.context.repo.owner;
            core.exportVariable('PR_NUMBER', prNumber);
            core.exportVariable('REPO_NAME', repo);
            core.exportVariable('REPO_OWNER', owner);
            console.log(`PR Number: ${prNumber}, Repo: ${owner}/${repo}`);
      - name: Comment on PR (Success)
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = process.env.PR_NUMBER;
            const buildVersion = process.env.version;
            const gitHash = process.env.git_hash;
            const comment = `Build completed for PR #${prNumber}. Version: ${buildVersion}, Commit: ${gitHash}.`;
            await github.rest.issues.createComment({
              owner: process.env.REPO_OWNER,
              repo: process.env.REPO_NAME,
              issue_number: prNumber,
              body: comment
            });
      - name: Comment on PR (Failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = process.env.PR_NUMBER;
            const issueUrl = `https://github.com/${process.env.REPO_OWNER}/${process.env.REPO_NAME}/issues/new?title=Build%20Failed%20for%20PR%20%23${prNumber}`;
            const comment = `Build failed for PR #${prNumber}. Please check the issue: ${issueUrl}`;
            await github.rest.issues.createComment({
              owner: process.env.REPO_OWNER,
              repo: process.env.REPO_NAME,
              issue_number: prNumber,
              body: comment
            });
